/**
 * The runtime half of `@typetorch/transformer`: `Reflect`, `Modding` and `t`, exported from the package root.
 *
 * `reflect.ts` and `modding.ts` are copies of `transformer/runtime-kit/` (the source of truth; keep them identical).
 * Code generated by the transformer in a game imports `Reflect` (and, when the game can't import `@rbxts/t` itself,
 * `t`) from `@typetorch/framework`. The framework ships inside every artifact, so each generation requires its own
 * copy of these modules and starts with an empty metadata store and id registry.
 */
export { Reflect } from "./reflect";
export { Modding } from "./modding";
export type { AbstractConstructor, ClassDescriptor, Constructor, MethodDescriptor, PropertyDescriptor } from "./modding";

// Generated guards fall back to this copy of `t` when the game resolves a different (or no) `@rbxts/t`.
export { t } from "@rbxts/t";
