import type { Modding } from "../reflection/modding";
import { Players } from "@rbxts/services";
import { $warn } from "rbxts-transform-debug";
import { clientDispatcher, registeredGuards, registeredLimits, serverDispatcher } from "./runtime";
import type { GuardTree } from "./types";

/**
 * A compatibility layer for `@flamework/networking` 1.x call sites (plans/19 item 5): the four handlers a Flamework game
 * exports (`ServerEvents`, `ClientEvents`, `ServerFunctions`, `ClientFunctions`), with Flamework's method names, on top
 * of TypeTorch's own network. Same guards (generated by @typetorch/transformer), limits, kernel remotes, packet
 * inspector and swap rules as `createNetwork`; only the names differ. Meant for moving a Flamework game over without
 * touching every call site; new code uses `createNetwork`.
 *
 * Not carried over: server -> client requests (ServerToClientFunctions: a client can't be trusted to answer; use an
 * event each way), middleware, `Networking.Unreliable` (sent reliably), `registerHandler`, and Flamework's error enum
 * (requests reject with TypeTorch's player-facing reasons).
 */

type Guard = (value: unknown) => boolean;
type FunctionParameters<T> = T extends (...args: infer P) => unknown ? P : never;
type FunctionReturn<T> = T extends (...args: never[]) => infer R ? R : never;
type Leaves<T> = ExtractMembers<T, Callback>;
type Namespaces<T> = ExcludeMembers<T, Callback>;

/** Server view of a server -> client event (Flamework's events `ServerSender`). Calling the leaf is `fire`. */
export interface FlameworkServerSender<A extends unknown[]> {
	(players: Player | Player[], ...args: A): void;
	/** Sends to one player or a list of players. */
	fire(players: Player | Player[], ...args: A): void;
	/** Sends to every player except the given one(s). */
	except(players: Player | Player[], ...args: A): void;
	/** Sends to every player (native: `fireAll`). */
	broadcast(...args: A): void;
}

/** Server view of a client -> server event (Flamework's events `ServerReceiver`). */
export interface FlameworkServerReceiver<A extends unknown[]> {
	/**
	 * Listens (native: `on`). Each call runs on its own thread, like Flamework's. The connection belongs to the running
	 * generation: a swap drops it with the generation, so it needs no trove; `Disconnect()` ends it earlier.
	 */
	connect(callback: (player: Player, ...args: A) => void): RBXScriptConnection;
	/** Runs this generation's listeners as if `player` had sent it: no network, no guard (native: `emit`). */
	predict(player: Player, ...args: A): void;
}

/** Client view of a client -> server event (Flamework's events `ClientSender`). Calling the leaf is `fire`. */
export interface FlameworkClientSender<A extends unknown[]> {
	(...args: A): void;
	fire(...args: A): void;
}

/** Client view of a server -> client event (Flamework's events `ClientReceiver`). */
export interface FlameworkClientReceiver<A extends unknown[]> {
	/** Listens (native: `on`); one thread per call; dropped with the generation (no trove needed). */
	connect(callback: (...args: A) => void): RBXScriptConnection;
	/** Runs this generation's listeners as if the server had sent it: no network traffic (native: `emit`). */
	predict(...args: A): void;
}

/** Server view of a client -> server request (Flamework's functions `ServerReceiver`). */
export interface FlameworkServerCallback<A extends unknown[], R> {
	/** The request's one handler (native: `handle`). It may return a Promise; the answer waits for it. */
	setCallback(callback: (player: Player, ...args: A) => R | Promise<R>): void;
	/** Runs the handler here, as if `player` had asked: no network, no guard. Rejects when no handler is set. */
	predict(player: Player, ...args: A): Promise<R>;
}

/** Client view of a client -> server request (Flamework's functions `ClientSender`). Calling the leaf is `invoke`. */
export interface FlameworkClientRequest<A extends unknown[], R> {
	(...args: A): Promise<R>;
	/** Rejects when the server doesn't answer in time: the leaf's `timeout`, else `defaultTimeout`, else 15 s. */
	invoke(...args: A): Promise<R>;
	/** `invoke` that gives up after `timeout` SECONDS (0.5 to 120; outside that it is clamped, with one warning). */
	invokeWithTimeout(timeout: number, ...args: A): Promise<R>;
}

/**
 * What a server -> client request (a leaf of ServerToClientFunctions) turns into: nothing to call. TypeTorch has no
 * server -> client requests, because a client can't be trusted to answer; use an event each way.
 */
export interface FlameworkUnsupportedRequest {
	readonly _typetorch_unsupported: "server -> client requests aren't supported by TypeTorch: use an event each way";
}

/** `ServerEvents`: senders for server -> client events, receivers for client -> server events. */
export type FlameworkServerEvents<C2S, S2C> = { [K in keyof Leaves<S2C>]: FlameworkServerSender<FunctionParameters<S2C[K]>> } & {
	[K in keyof Leaves<C2S>]: FlameworkServerReceiver<FunctionParameters<C2S[K]>>;
} & { [K in keyof Namespaces<S2C>]: FlameworkServerEvents<K extends keyof C2S ? C2S[K] : {}, S2C[K]> } & {
	[K in keyof Namespaces<C2S>]: FlameworkServerEvents<C2S[K], K extends keyof S2C ? S2C[K] : {}>;
};

/** `ClientEvents`: senders for client -> server events, receivers for server -> client events. */
export type FlameworkClientEvents<C2S, S2C> = { [K in keyof Leaves<C2S>]: FlameworkClientSender<FunctionParameters<C2S[K]>> } & {
	[K in keyof Leaves<S2C>]: FlameworkClientReceiver<FunctionParameters<S2C[K]>>;
} & { [K in keyof Namespaces<C2S>]: FlameworkClientEvents<C2S[K], K extends keyof S2C ? S2C[K] : {}> } & {
	[K in keyof Namespaces<S2C>]: FlameworkClientEvents<K extends keyof C2S ? C2S[K] : {}, S2C[K]>;
};

/** `ServerFunctions`: handlers for client -> server requests. */
export type FlameworkServerFunctions<C2S, S2C> = {
	[K in keyof Leaves<C2S>]: FlameworkServerCallback<FunctionParameters<C2S[K]>, FunctionReturn<C2S[K]>>;
} & { [K in keyof Leaves<S2C>]: FlameworkUnsupportedRequest } & {
	[K in keyof Namespaces<C2S>]: FlameworkServerFunctions<C2S[K], K extends keyof S2C ? S2C[K] : {}>;
} & { [K in keyof Namespaces<S2C>]: FlameworkServerFunctions<K extends keyof C2S ? C2S[K] : {}, S2C[K]> };

/** `ClientFunctions`: requests the client sends. */
export type FlameworkClientFunctions<C2S, S2C> = {
	[K in keyof Leaves<C2S>]: FlameworkClientRequest<FunctionParameters<C2S[K]>, FunctionReturn<C2S[K]>>;
} & { [K in keyof Leaves<S2C>]: FlameworkUnsupportedRequest } & {
	[K in keyof Namespaces<C2S>]: FlameworkClientFunctions<C2S[K], K extends keyof S2C ? S2C[K] : {}>;
} & { [K in keyof Namespaces<S2C>]: FlameworkClientFunctions<K extends keyof C2S ? C2S[K] : {}, S2C[K]> };

/** The `config` of Flamework's `createServer` / `createClient`. Only `defaultTimeout` does something here. */
export interface FlameworkCompatConfig {
	/** Not supported (warned once): every client message is checked by its generated guard and setNetworkLimits. */
	middleware?: unknown;
	/** Not supported (warned once): guards always run on the server. */
	disableIncomingGuards?: boolean;
	/** Ignored: the dev menu's Network > Packets shows every refused message. */
	warnOnInvalidGuards?: boolean;
	/** Functions, `createClient`: seconds an `invoke` waits when its leaf has no `timeout` (else 15). */
	defaultTimeout?: number;
}

/** Flamework's `GlobalEvents` / `GlobalFunctions`: `createServer()` / `createClient()` return the handlers. */
export interface FlameworkGlobal<S, C> {
	createServer(config?: FlameworkCompatConfig): S;
	createClient(config?: FlameworkCompatConfig): C;
}

export interface FlameworkCompat<C2SEvents, S2CEvents, C2SFunctions, S2CFunctions> {
	readonly ServerEvents: FlameworkServerEvents<C2SEvents, S2CEvents>;
	readonly ClientEvents: FlameworkClientEvents<C2SEvents, S2CEvents>;
	readonly ServerFunctions: FlameworkServerFunctions<C2SFunctions, S2CFunctions>;
	readonly ClientFunctions: FlameworkClientFunctions<C2SFunctions, S2CFunctions>;
	/** For code written as `GlobalEvents.createServer({})`: the same handlers as ServerEvents / ClientEvents. */
	readonly GlobalEvents: FlameworkGlobal<FlameworkServerEvents<C2SEvents, S2CEvents>, FlameworkClientEvents<C2SEvents, S2CEvents>>;
	readonly GlobalFunctions: FlameworkGlobal<
		FlameworkServerFunctions<C2SFunctions, S2CFunctions>,
		FlameworkClientFunctions<C2SFunctions, S2CFunctions>
	>;
}

// Runtime --------------------------------------------------------------------------------------------------------------

/** What `connect` returns: shaped like an RBXScriptConnection (`Connected`, `Disconnect`), so troves take it too. */
class CompatConnection {
	Connected = true;
	constructor(private readonly disconnect: () => void) {}
	Disconnect() {
		if (!this.Connected) return;
		this.Connected = false;
		this.disconnect();
	}
	Destroy() {
		this.Disconnect();
	}
}

/**
 * Each listener call on its own thread (Flamework ran listeners through a BindableEvent): one that yields doesn't hold
 * up the next. A listener that throws is warned and counted, like a native one.
 */
function threaded(path: string, callback: Callback, countError: () => void): Callback {
	const run = (...args: unknown[]) => {
		const [ok, err] = pcall(callback, ...args);
		if (!ok) {
			countError();
			$warn(`[net] ${path} listener threw: ${err}`);
		}
	};
	return (...args: unknown[]) => {
		task.spawn(run, ...args);
	};
}

function playerList(players: Player | Player[]): Player[] {
	return typeIs(players, "Instance") ? [players] : players;
}

/** The server end of one event leaf (both directions; the types decide which methods a leaf shows). */
class ServerEventLeaf {
	constructor(readonly path: string) {}
	fire(players: Player | Player[], ...args: unknown[]) {
		const dispatcher = serverDispatcher();
		for (const player of playerList(players)) dispatcher.send(player, this.path, args);
	}
	except(players: Player | Player[], ...args: unknown[]) {
		const dispatcher = serverDispatcher();
		const skip = playerList(players);
		for (const player of Players.GetPlayers()) {
			if (!skip.includes(player)) dispatcher.send(player, this.path, args);
		}
	}
	broadcast(...args: unknown[]) {
		serverDispatcher().sendAll(this.path, args);
	}
	connect(callback: (player: Player, ...args: unknown[]) => void) {
		const dispatcher = serverDispatcher();
		const path = this.path;
		const listener = threaded(path, callback, () => (dispatcher.stat(path).errors += 1));
		return new CompatConnection(dispatcher.addListener(path, listener));
	}
	predict(player: Player, ...args: unknown[]) {
		serverDispatcher().emit(player, this.path, args);
	}
}

/** The client end of one event leaf. */
class ClientEventLeaf {
	constructor(readonly path: string) {}
	fire(...args: unknown[]) {
		clientDispatcher().fire(this.path, args);
	}
	connect(callback: (...args: unknown[]) => void) {
		const dispatcher = clientDispatcher();
		const path = this.path;
		const listener = threaded(path, callback, () => (dispatcher.stat(path).errors += 1));
		return new CompatConnection(dispatcher.addListener(path, listener));
	}
	predict(...args: unknown[]) {
		clientDispatcher().emit(this.path, args);
	}
}

/** The server end of one request leaf. */
class ServerFunctionLeaf {
	private callback?: (player: Player, ...args: unknown[]) => unknown;
	constructor(readonly path: string) {}
	setCallback(callback: (player: Player, ...args: unknown[]) => unknown) {
		this.callback = callback;
		serverDispatcher().setHandler(this.path, callback);
	}
	predict(player: Player, ...args: unknown[]): Promise<unknown> {
		const callback = this.callback;
		if (callback === undefined) return Promise.reject(`${this.path} has no callback (setCallback) in this generation`);
		return Promise.try(() => callback(player, ...args));
	}
}

/** Flamework `createClient({ defaultTimeout })`, shared by every request leaf of one compat network. */
interface RequestSettings {
	defaultTimeout?: number;
}

/** The client end of one request leaf. */
class ClientFunctionLeaf {
	constructor(
		readonly path: string,
		private readonly settings: RequestSettings,
	) {}
	invoke(...args: unknown[]): Promise<unknown> {
		const seconds = registeredLimits.get(this.path)?.timeout === undefined ? this.settings.defaultTimeout : undefined;
		return clientDispatcher().invoke(this.path, args, seconds);
	}
	invokeWithTimeout(timeout: number, ...args: unknown[]): Promise<unknown> {
		return clientDispatcher().invoke(this.path, args, timeout);
	}
}

// Calling a leaf like a function (`ServerEvents.x(player, ...)`, `ClientFunctions.y(...)`) is Flamework's shorthand
// for fire / invoke. roblox-ts compiles those calls without `self`, so the classes get a `__call` metamethod (every
// instance's metatable is its class).
interface Callable {
	__call: Callback;
}
(ServerEventLeaf as unknown as Callable).__call = (leaf: ServerEventLeaf, players: Player | Player[], ...args: unknown[]) =>
	leaf.fire(players, ...args);
(ClientEventLeaf as unknown as Callable).__call = (leaf: ClientEventLeaf, ...args: unknown[]) => leaf.fire(...args);
(ClientFunctionLeaf as unknown as Callable).__call = (leaf: ClientFunctionLeaf, ...args: unknown[]) => leaf.invoke(...args);

class CompatGlobal {
	constructor(
		private readonly server: object,
		private readonly client: object,
		private readonly settings?: RequestSettings,
	) {}
	createServer(config?: FlameworkCompatConfig) {
		checkConfig(config);
		return this.server;
	}
	createClient(config?: FlameworkCompatConfig) {
		checkConfig(config);
		if (this.settings && config?.defaultTimeout !== undefined) this.settings.defaultTimeout = config.defaultTimeout;
		return this.client;
	}
}

let warnedConfig = false;
function checkConfig(config: FlameworkCompatConfig | undefined) {
	if (config === undefined || warnedConfig) return;
	const middleware = config.middleware;
	const hasMiddleware = typeIs(middleware, "table") && next(middleware)[0] !== undefined;
	if (hasMiddleware || config.disableIncomingGuards === true) {
		warnedConfig = true;
		$warn("[net] Flamework compat: middleware and disableIncomingGuards aren't supported and are ignored (guards always run)");
	}
}

function flatten(tree: unknown, prefix: string, into: Map<string, Guard>) {
	for (const [key, value] of pairs(tree as Record<string, unknown>)) {
		const path = prefix === "" ? (key as string) : `${prefix}.${key}`;
		if (typeIs(value, "function")) into.set(path, value as Guard);
		else if (typeIs(value, "table")) flatten(value, path, into);
	}
}

/** Puts a leaf at its dotted path in `root` (namespaces are plain tables); the same path twice is the same leaf. */
function place<T extends object>(root: Record<string, unknown>, path: string, create: () => T): T {
	const parts = path.split(".");
	let node = root;
	for (let index = 0; index < parts.size() - 1; index++) {
		const part = parts[index];
		let child = node[part] as Record<string, unknown> | undefined;
		if (child === undefined) {
			child = {};
			node[part] = child;
		}
		node = child;
	}
	const name = parts[parts.size() - 1];
	const existing = node[name];
	if (existing !== undefined) return existing as T;
	const leaf = create();
	node[name] = leaf;
	return leaf;
}

/**
 * Flamework networking names on TypeTorch's network, for moving a `@flamework/networking` game over without rewriting
 * its call sites:
 *
 * ```ts
 * export const { ServerEvents, ClientEvents, ServerFunctions, ClientFunctions } = createFlameworkCompat<
 * 	ClientToServerEvents, ServerToClientEvents, ClientToServerFunctions, ServerToClientFunctions
 * >();
 * // or, for code written as GlobalEvents.createServer({}):
 * export const GlobalEvents = createFlameworkCompat<ClientToServerEvents, ServerToClientEvents>().GlobalEvents;
 * ```
 *
 * `connect` (= `on`, returns a connection), `fire` (one player or a list), `broadcast` (= `fireAll`), `except`,
 * `predict` (= `emit`), `setCallback` (= `handle`, may return a Promise), `invoke`, `invokeWithTimeout` (seconds), and
 * calling a leaf directly (= `fire` / `invoke`). Events and functions share one path space (`Spin.request` can't be
 * both). Guards are generated per leaf, both directions, and checked on the server like `createNetwork`'s;
 * `setNetworkLimits` tunes the same leaves. Server -> client requests (ServerToClientFunctions) aren't supported.
 *
 * @metadata macro network
 */
export function createFlameworkCompat<
	C2SEvents extends object,
	S2CEvents extends object,
	C2SFunctions extends object = {},
	S2CFunctions extends object = {},
>(
	clientToServerEvents?: Modding.Many<GuardTree<C2SEvents>>,
	serverToClientEvents?: Modding.Many<GuardTree<S2CEvents>>,
	clientToServerFunctions?: Modding.Many<GuardTree<C2SFunctions>>,
): FlameworkCompat<C2SEvents, S2CEvents, C2SFunctions, S2CFunctions> {
	assert(
		clientToServerEvents && serverToClientEvents && clientToServerFunctions,
		"createFlameworkCompat: guards were not generated (is @typetorch/transformer in the tsconfig plugins?)",
	);
	const c2sEvents = new Map<string, Guard>();
	const s2cEvents = new Map<string, Guard>();
	const c2sFunctions = new Map<string, Guard>();
	flatten(clientToServerEvents, "", c2sEvents);
	flatten(serverToClientEvents, "", s2cEvents);
	flatten(clientToServerFunctions, "", c2sFunctions);

	// One guard per path: an event and a request with the same path would check one with the other's guard.
	for (const [path] of c2sFunctions) {
		if (c2sEvents.has(path)) error(`[net] createFlameworkCompat: "${path}" is both an event and a function; rename one`, 2);
	}
	const register = (guards: Map<string, Guard>) => {
		for (const [path, guard] of guards) {
			if (registeredGuards.has(path)) error(`[net] createFlameworkCompat: "${path}" is already declared by another network`, 3);
			registeredGuards.set(path, guard);
		}
	};
	register(c2sEvents);
	register(c2sFunctions);

	const serverEvents: Record<string, unknown> = {};
	const clientEvents: Record<string, unknown> = {};
	for (const paths of [c2sEvents, s2cEvents]) {
		for (const [path] of paths) {
			place(serverEvents, path, () => new ServerEventLeaf(path));
			place(clientEvents, path, () => new ClientEventLeaf(path));
		}
	}
	const settings: RequestSettings = {};
	const serverFunctions: Record<string, unknown> = {};
	const clientFunctions: Record<string, unknown> = {};
	for (const [path] of c2sFunctions) {
		place(serverFunctions, path, () => new ServerFunctionLeaf(path));
		place(clientFunctions, path, () => new ClientFunctionLeaf(path, settings));
	}

	type Compat = FlameworkCompat<C2SEvents, S2CEvents, C2SFunctions, S2CFunctions>;
	return {
		ServerEvents: serverEvents as unknown as Compat["ServerEvents"],
		ClientEvents: clientEvents as unknown as Compat["ClientEvents"],
		ServerFunctions: serverFunctions as unknown as Compat["ServerFunctions"],
		ClientFunctions: clientFunctions as unknown as Compat["ClientFunctions"],
		GlobalEvents: new CompatGlobal(serverEvents, clientEvents) as unknown as Compat["GlobalEvents"],
		GlobalFunctions: new CompatGlobal(serverFunctions, clientFunctions, settings) as unknown as Compat["GlobalFunctions"],
	};
}
