/**
 * Generates src/devtools/explorer/icons.ts: the Studio explorer icon index and sort order per class.
 *
 * Source: ReflectionMetadata.xml as mirrored by MaximumADHD/Roblox-Client-Tracker (branch "roblox"):
 *   https://github.com/MaximumADHD/Roblox-Client-Tracker/blob/roblox/ReflectionMetadata.xml
 * Each <Item class="ReflectionMetadataClass"> holds Name, ExplorerImageIndex and ExplorerOrder. The index counts 16x16
 * icons in the client's content/textures/ClassImages.PNG (a 2352x16 strip). The explorer uses assets/class-icons.png,
 * the same icons repacked into a 32-column grid (live clients downscale textures wider than 1024 px), so an index maps
 * to column index % 32, row floor(index / 32). The generated table is just numbers.
 *
 * Usage (from framework/): bun scripts/gen-explorer-icons.ts [--xml path/to/ReflectionMetadata.xml]
 * Re-run when Roblox adds classes; commit the generated file.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE = "https://raw.githubusercontent.com/MaximumADHD/Roblox-Client-Tracker/roblox/ReflectionMetadata.xml";
const OUT = join(import.meta.dir, "..", "src", "devtools", "explorer", "icons.ts");

const xmlFlag = process.argv.indexOf("--xml");
const xml =
	xmlFlag !== -1
		? await Bun.file(process.argv[xmlFlag + 1]).text()
		: await fetch(SOURCE).then((response) => {
				if (!response.ok) throw new Error(`GET ${SOURCE}: ${response.status}`);
				return response.text();
			});

// Only the first <Properties> block of a class item belongs to the class (nested items are its members).
const classPattern = /<Item class="ReflectionMetadataClass">\s*<Properties>([\s\S]*?)<\/Properties>/g;
const field = (block: string, name: string) => block.match(new RegExp(`<string name="${name}">([^<]*)</string>`))?.[1];

const entries = new Map<string, [number, number]>();
for (const [, block] of xml.matchAll(classPattern)) {
	const name = field(block, "Name");
	if (!name) continue;
	const icon = Number(field(block, "ExplorerImageIndex") ?? -1);
	const order = Number(field(block, "ExplorerOrder") ?? -1);
	if (icon < 0 && order < 0) continue;
	entries.set(name, [Number.isFinite(icon) ? icon : -1, Number.isFinite(order) ? order : -1]);
}
if (entries.size < 100) throw new Error(`only ${entries.size} classes parsed; did the XML format change?`);

const names = [...entries.keys()].sort();
const withIcon = names.filter((name) => entries.get(name)![0] >= 0).length;
const lines: string[] = [];
let line = "\t";
for (const name of names) {
	const [icon, order] = entries.get(name)!;
	const key = /^[A-Za-z_]\w*$/.test(name) ? name : JSON.stringify(name);
	const item = `${key}: [${icon}, ${order}], `;
	if (line.length + item.length > 118) {
		lines.push(line.trimEnd());
		line = "\t";
	}
	line += item;
}
lines.push(line.trimEnd());

const output = `// Generated by scripts/gen-explorer-icons.ts from Roblox-Client-Tracker ReflectionMetadata.xml. Do not edit.
// ${names.length} classes, ${withIcon} with an icon. Value: [ExplorerImageIndex, ExplorerOrder]; -1 = not set (inherit).

/** Icon index (row-major in the 32-column 16 px grid of assets/class-icons.png) and explorer sort order, per class. */
export const CLASS_ICONS: Record<string, [icon: number, order: number]> = {
${lines.join("\n")}
};
`;
writeFileSync(OUT, output);
console.log(`wrote ${OUT}: ${names.length} classes, ${withIcon} with an icon`);
